hibernate.dialect = org.hibernate.dialect.MySQLDialect

hibernate.dialect.storage_engine = innodb

hibernate.connection.driver_class = com.mysql.cj.jdbc.Driver


For local DBServer
Change name of database. [sample_database} to your own database name.
Use your own credentials
hibernate.connection.url = jdbc:mysql://localhost/chess_final_check?createDatabaseIfNotExist=true&amp&serverTimezone=Europe/Amsterdam&amp&autoReconnect=true&amp&allowPublicKeyRetrieval=true&useSSL=false
hibernate.connection.username = root
hibernate.connection.password = admin

#**WARNING*WARNING**LIVE SERVER DATABASE URL**

hibernate.temp.use_jdbc_metadata_defaults = true

#property for production servers set to false
hibernate.show_sql = false

#For production/staging servers no auto DDL. Run SQL-Script manually on Staging DBServer
hibernate.hbm2ddl.auto = update

?hibernate.current_session_context_class = org.hibernate.context.internal.ThreadLocalSessionContext
hibernate.current_session_context_class = thread

hibernate.c3p0.min_size=20
hibernate.c3p0.max_size=100
hibernate.c3p0.acquire_increment=5
hibernate.c3p0.timeout=1800
hibernate.c3p0.max_statements=500